### ISSUE TITLE
Elasticsearch keystore test failures in JDK22

### ISSUE THREAD

**Issue by jan-elastic** [elastic/elasticsearch#104858]
**Build scan:**
https://gradle-enterprise.elastic.co/s/j2hllfv26rfzi/tests/:x-pack:plugin:security:qa:multi-cluster:v7.17.18%23bwcTest/org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityBwcRestIT

**Reproduction line:**
```
null
```

**Applicable branches:**
main, 8.12

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityBwcRestIT#classMethod`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('classMethod'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityBwcRestIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([4E404BA9DD1E8282]:0)
  at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.execute(DefaultLocalClusterHandle.java:264)
  at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.execute(DefaultLocalClusterHandle.java:269)
  at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.start(DefaultLocalClusterHandle.java:72)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:45)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

  Caused by: java.lang.RuntimeException: Execution of elasticsearch-keystore failed with exit code 1

    at org.elasticsearch.test.cluster.local.AbstractLocalClusterFactory$Node.runToolScript(AbstractLocalClusterFactory.java:789)
    at org.elasticsearch.test.cluster.local.AbstractLocalClusterFactory$Node.createKeystore(AbstractLocalClusterFactory.java:465)
    at org.elasticsearch.test.cluster.local.AbstractLocalClusterFactory$Node.start(AbstractLocalClusterFactory.java:169)
    at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.lambda$start$0(DefaultLocalClusterHandle.java:72)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
    at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:676)
    at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:264)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:785)
    at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.lambda$start$1(DefaultLocalClusterHandle.java:72)
    at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.lambda$execute$16(DefaultLocalClusterHandle.java:270)
    at java.util.concurrent.ForkJoinTask$AdaptedInterruptibleCallable.compute(ForkJoinTask.java:1689)
    at java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

```

**Comment by slobodanadamovic** [comment]
This issue is reproducible on openjdk22 (which is not yet officially supported) and seems like a duplicate of https://github.com/elastic/elasticsearch/issues/103963.

**Comment by piergm** [comment]
Another instance occurred today: https://gradle-enterprise.elastic.co/s/danbligjgug4q

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/mbhe5taqmfxkq/

**Comment by volodk85** [comment]
One more:
https://gradle-enterprise.elastic.co/s/cskmoswlgucrm/console-log/task/:x-pack:plugin:security:qa:multi-cluster:v7.17.19%23bwcTest?anchor=61&page=1

**Comment by iverase** [comment]
https://gradle-enterprise.elastic.co/s/3jp3tmutlrebm

**Comment by kingherc** [comment]
More at [elasticsearch / periodic / main / openjdk22 / bwcTestSnapshots / java-matrix](https://gradle-enterprise.elastic.co/s/mao5kvneoobgi)

**Comment by kingherc** [comment]
Another one at [elasticsearch / periodic / main / openjdk22 / bwcTestSnapshots / java-matrix](https://gradle-enterprise.elastic.co/s/4atc55llcyidw)

I'll mute the whole test suite since this is happening a lot lately! Security team, please revert the mute if that's not OK.

**Comment by benwtrent** [comment]
8.12 & 7.17 yaml rest test build with JDK22 all just failed with issue. 

`Process 'command './bin/elasticsearch-keystore'' finished with non-zero exit value 1`

JDK22 just isn't playing nice with this.

I could list all the build failures, but the list would be rather long. Seems like we need some more work to do for jdk22 to be fully supported.

**Comment by benwtrent** [comment]
I am moving and relabeling this issue. Numerous test suites are failing JDK22 due to keystore exiting with a non-zero status.

**Comment by rjernst** [comment]
It looks like these are all the result of a change to Console in JDK 22 which we already addressed in https://github.com/elastic/elasticsearch/pull/103614, but was not backported to 8.12 or 7.17. I'll work on backporting to those branches.

**Comment by rjernst** [comment]
8.12: https://github.com/elastic/elasticsearch/pull/106049
7.17: https://github.com/elastic/elasticsearch/pull/106051

**Comment by williamrandolph** [comment]
Since the fix has been backported and we haven't seen issues, we're closing this as fixed.

**Comment by thecoop** [comment]
The re-enabled test is still failing for every bwc version - eg https://gradle-enterprise.elastic.co/s/uqjyfjzhvrcng/tests/task/:x-pack:plugin:security:qa:multi-cluster:v8.4.3%23bwcTest/details/org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityBwcRestIT?top-execution=1

**Comment by mosche** [comment]
The issue seems to be that we're also forcing JDK 22 to run the old distributions in bwc tests.
Obviously, these are not build to support JDK 22 yet.
