### ISSUE TITLE
Missing field filter not working

### ISSUE THREAD

**Issue by dling** [elastic/elasticsearch#10590]
I have an Elasticsearch 1.5.0 environment with 3 nodes and 3 shards of each index.

I have the following document indexed:

```json
{
  "_index": "content-1",
  "_type": "share-site-article",
  "_id": "5c7aca72-f1fd-48dd-b2ee-1ed6d3ef134b",
  "_source": {
    "preamble": "X and Y presents",
    "nativeAdCampaignName": "Company",
    "_site": "docs"
  }
}
```

However when I make queries and combine it with using the missing field filter the actual missing field filter is not being used.

```json
POST /content/_search
{
    "query": {
     "match": {
        "_all": "X and Y presents"
    }
   },
   "filter": {
      "and": {
         "filters": [
            {
               "missing": {
                  "field": "nativeAdCampaignName"
               }
            },             
            {
               "term": {
                  "_id": "5c7aca72-f1fd-48dd-b2ee-1ed6d3ef134b"
               }
            },
            {
               "term": {
                  "_site": "docs"
               }
            }
         ]
      }
   }
}
```

Response output for that query:

```json
 {
   "took": 38,
   "timed_out": false,
   "_shards": {
      "total": 6,
      "successful": 6,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1.8740479,
      "hits": [
         {
            "_index": "content-1",
            "_type": "share-site-article",
            "_id": "5c7aca72-f1fd-48dd-b2ee-1ed6d3ef134b",
            "_score": 1.8740479,
            "_source": {
               "preamble": "X and Y presents",
               "nativeAdCampaignName": "Company",
               "_site": "docs"
            }
         }
      ]
   }
}
```

The query above should not return the document, since I am querying for document that has missing field values in the specific field 'nativeAdCampaignName'.

The field I'm unable to use with missing field is indeed indexed, i.e. I can search on that field and have the document returned.

(A problematic implication is that I cannot reproduce this problem in a local single-node environment running same ES version and mapping. There's different JVM versions and difference in number of nodes though.)

This environment runs on OpenJDK 64-Bit Server VM, 1.7.0_75.

Any ideas why this happens?

**Comment by clintongormley** [comment]
Hi @dling 

First, you shouldn't be using `filter` here.  This filter is only applied AFTER your query has been run and aggregations have been calculated.  So it removes results from the `hits`, but the results will still be taken into account by aggregations.  Instead, you should use a `filtered` query.

Next, I note that you're querying the `content` index, but the document is actually in `content-1`. I assume `content` is actually an alias? (This should work regardless)

Then, like you, I'm unable to replicate this locally on 1.5.0.  Please could you upload the output of the following:

Mapping for all fields:

    GET content/_mapping

Mapping for `_field_names`:

    GET content/_mapping/field/_field_names?include_defaults

Explanation of query: 

    POST /content-1/_validate/query?explain

Values in `_field_names` for this document: 

    POST /content/_search
    {
      "query": {
        "term": {
          "_id": "5c7aca72-f1fd-48dd-b2ee-1ed6d3ef134b"
        }
      },
      "fielddata_fields": ["_field_names"]
    }

An explanation of how this document matched:

    POST /content-1/share-site-article/5c7aca72-f1fd-48dd-b2ee-1ed6d3ef134b/_explain
    {
      "query": {
        "filtered": {
          "query": {
            "match": {
              "_all": "X and Y presents"
            }
          },
          "filter": {
            "and": {
              "filters": [
                {
                  "missing": {
                    "field": "nativeAdCampaignName"
                  }
                },
                {
                  "term": {
                    "_id": "5c7aca72-f1fd-48dd-b2ee-1ed6d3ef134b"
                  }
                },
                {
                  "term": {
                    "_site": "docs"
                  }
                }
              ]
            }
          }
        }
      }
    }

**Comment by rjernst** [comment]
@dling Was your index created before 1.3? It may be the same issues as #10414 which was fixed in #10268 for 1.5.1.

**Comment by dling** [comment]
Thanks a lot for the responses. Yes the index was indeed created on an earlier version, I believe before 1.3. 

I will upgrade to 1.5.1 in the next few days and see how that works out, and if it doesn't solve it I'll upload the requested output.

**Comment by HenleyChiu** [comment]
FYI,

I don't think this was ever fixed in 1.5.1 as I've ran into the same problem with the latest version.

I assume this is going to be in a future release?

**Comment by HenleyChiu** [comment]
@dling I'm not sure if you're lucky, but as a workaround, you can replace the missing filter with a bool filter. This is only if you know the value can be from a limited set of possible values.

"filter":{	"bool" : {
                "must_not" : [
                    {
                        "term" : { "nativeAdCampaignName" : "VALUE" }
                    }
                ]
            }
    }

**Comment by rjernst** [comment]
@HenleyChiu Can you describe in more detail what exact behavior you are seeing? Do you have an index created before 1.3.0?

@dling Were you able to upgrade to 1.5.1 and confirm it was the same issue as in #10414?

**Comment by dling** [comment]
**The cluster was upgraded to 1.5.1 but this issue remains.**

(We also upgraded Java to OpenJDK Runtime Environment (build 1.8.0_45-b13).

@HenleyChiu Thanks for the workaround suggestion but we have a big variety of possible values so that wouldn't be manageable in our case.

@rjernst I've read the #10414 issue, yes these issues are likely linked and related. Do you see a possibility that this could be resolved in an upcoming 1.5.x release or is the re-indexing to a new index the recommended workaround ? I'd have to start looking into the possibilities of that.

@clintongormley The `filtered` query is among the types I tried initially but it has the same problem. The `content` is indeed an index alias yes. Are you on @rjernst on top of what causes this issue or would any of the requested debug information help ?

**Comment by clintongormley** [comment]
@rjernst I can confirm that the `missing/exists` functionality is broken when moving from (eg) and index created in 1.1.0 to 1.5.0, 1.5.1, or 1.5.2.

**Comment by briar354** [comment]
Hi.
We upgraded to 1.5.1 this weekend and now the missing filter does not work any longer. Can I provide more data for you that might help in your investigations or have you already located the problem?

**Comment by rjernst** [comment]
This should now be fixed, and will be in 1.5.3.  The issue was already fixed on master, but the missing filter portion of the fix was not correctly tested or backported.

**Comment by briar354** [comment]
When is 1.5.3 scheduled for?

**Comment by clintongormley** [comment]
As a workaround, you can use:

    { "not": { "exists": { "field": "field_name" }}}

**Comment by alainperry** [comment]
@clintongormley I'm on 1.5.2 with the same problem, and the exists filter is affected as well. Which means that this workaround does not work either.

**Comment by dling** [comment]
Was the fix included in 1.6.0?

**Comment by s1monw** [comment]
@dling yes I will add the label

**Comment by alainperry** [comment]
My "missing" filter works again. Thank you.

**Comment by clintongormley** [comment]
thanks for letting us know @alainperry

**Comment by nilsga** [comment]
Does this also affect the `missing` aggregation?

**Comment by jpountz** [comment]
No, the `missing` aggregation works in a very different way.
