### ISSUE TITLE
[CI] UpgradeWithOldIndexSettingsIT testMapperDynamicIndexSetting {cluster=UPGRADED} failing

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#109591]
This seems to be failing for many 7.x branches whenever the `test-full-bwc` label is applied.

It seems to fail with something like:

```
[2024-06-11T12:33:55,711][WARN ][o.e.c.r.a.AllocationService] [test-cluster-0] failing shard [failed shard, shard [my-index][0], node[ueR33VA_T-eo7EfZu3ZEGA], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=Rd7Y89jHSZy1kwaOHFd_Zg], unassigned_info[[reason=INDEX_CREATED], at[2024-06-11T16:33:55.174Z], delayed=false, allocation_status[no_attempt]], message [failed to create index], failure [IllegalArgumentException[Setting index.mapper.dynamic was removed after version 6.0.0]], markAsStale [true]]	
java.lang.IllegalArgumentException: Setting index.mapper.dynamic was removed after version 6.0.0	
	at org.elasticsearch.index.mapper.MapperService.<init>(MapperService.java:180) ~[elasticsearch-7.9.3.jar:7.9.3]	
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:194) ~[elasticsearch-7.9.3.jar:7.9.3]	
	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:440) ~[elasticsearch-7.9.3.jar:7.9.3]	
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:656) ~[elasticsearch-7.9.3.jar:7.9.3]	
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:559) ~[elasticsearch-7.9.3.jar:7.9.3]
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/lnh7x6ee4cv66/tests/:qa:full-cluster-restart:v7.16.3%23bwcTest/org.elasticsearch.upgrades.UpgradeWithOldIndexSettingsIT/testMapperDynamicIndexSetting%20%7Bcluster=UPGRADED%7D

**Reproduction line:**
```
./gradlew ':qa:full-cluster-restart:v7.16.3#bwcTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeWithOldIndexSettingsIT" -Dtests.method="testMapperDynamicIndexSetting {cluster=UPGRADED}" -Dtests.seed=837B09E956DB441B -Dtests.bwc=true -Dtests.locale=da -Dtests.timezone=Asia/Chongqing -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.upgrades.UpgradeWithOldIndexSettingsIT#testMapperDynamicIndexSetting {cluster=UPGRADED}`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testMapperDynamicIndexSetting%20%7Bcluster%3DUPGRADED%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.upgrades.UpgradeWithOldIndexSettingsIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([837B09E956DB441B:3D36A2616312A83]:0)
  at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.execute(DefaultLocalClusterHandle.java:269)
  at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.writeUnicastHostsFile(DefaultLocalClusterHandle.java:250)
  at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.waitUntilReady(DefaultLocalClusterHandle.java:193)
  at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.upgradeToVersion(DefaultLocalClusterHandle.java:166)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster.upgradeToVersion(DefaultLocalElasticsearchCluster.java:155)
  at org.elasticsearch.upgrades.ParameterizedFullClusterRestartTestCase.maybeUpgrade(ParameterizedFullClusterRestartTestCase.java:105)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

  Caused by: java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details.

    at org.elasticsearch.test.cluster.local.AbstractLocalClusterFactory$Node.lambda$waitUntilReady$0(AbstractLocalClusterFactory.java:274)
    at org.elasticsearch.test.cluster.util.Retry.lambda$retryUntilTrue$0(Retry.java:28)
    at java.lang.Thread.run(Thread.java:1570)

```

**Comment by rjernst** [comment]
I suspect this is fallout from https://github.com/elastic/elasticsearch/issues/96075. cc @martijnvg

**Comment by benwtrent** [comment]
https://github.com/elastic/elasticsearch/pull/109574 should fix it

**Comment by martijnvg** [comment]
I don't think this bwc test is no longer an issue on main and 8.14 branches? I don't see new build failures that have the commit that get merged with #109574. Locally I also don't observe `UpgradeWithOldIndexSettingsIT` failures in the full cluster restart qa module with old cluster versions prior to 7.17.22.

**Comment by pxsalehi** [comment]
This has been failing a lot today.

**Comment by martijnvg** [comment]
Right, I still see new failures, but it looks like it using a commit prior the commit that was merged yesterday that addresses these failures. For example look at this recent failure: https://gradle-enterprise.elastic.co/s/l7gwjrxmj74uo it is based in this [commit](https://github.com/elastic/elasticsearch/commit/829ab67d579133aacf3e7eda413b2aca00b5c363) in 8.14 branch.

**Comment by martijnvg** [comment]
I also manually triggered the 8.14 periodic build with a new commit and it passed: 

<img width="1165" alt="image" src="https://github.com/elastic/elasticsearch/assets/580421/3fc68383-580c-4690-be5c-7ffabf39c2cb">

**Comment by pxsalehi** [comment]
Wonderful! Thank you! :)

**Comment by martijnvg** [comment]
No more new failures for 3 days.
