### ISSUE TITLE
Kibana highlighting issue not fixed?

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#11599]
New 1.6.0 install with new indices, in Kibana discover searching for "execute":
```
[2015-06-11 13:18:59,718][DEBUG][action.search.type       ] [Laura Dean] [29] Failed to execute fetch phase
org.elasticsearch.search.fetch.FetchPhaseExecutionException: [logstash-2015.06.11][4]: query[filtered(_all:execute)->BooleanFilter(+cache(@timestamp:[1433938739612 TO 1434025139612]
))],from[0],size[500],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@31c250a5>!]: Fetch Failed [Failed to highlight field [m
essage.raw]]
        at org.elasticsearch.search.highlight.PlainHighlighter.highlight(PlainHighlighter.java:133)
        at org.elasticsearch.search.highlight.HighlightPhase.hitExecute(HighlightPhase.java:133)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:194)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:504)
        at org.elasticsearch.search.action.SearchServiceTransportAction$17.call(SearchServiceTransportAction.java:452)
        at org.elasticsearch.search.action.SearchServiceTransportAction$17.call(SearchServiceTransportAction.java:449)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 173493
        at org.apache.lucene.index.memory.MemoryIndex.addField(MemoryIndex.java:493)
        at org.apache.lucene.index.memory.MemoryIndex.addField(MemoryIndex.java:396)
        at org.apache.lucene.index.memory.MemoryIndex.addField(MemoryIndex.java:371)
        at org.apache.lucene.index.memory.MemoryIndex.addField(MemoryIndex.java:351)
        at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getLeafContext(WeightedSpanTermExtractor.java:360)
        at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:216)
        at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getWeightedSpanTerms(WeightedSpanTermExtractor.java:474)
        at org.apache.lucene.search.highlight.QueryScorer.initExtractor(QueryScorer.java:217)
        at org.apache.lucene.search.highlight.QueryScorer.init(QueryScorer.java:186)
        at org.apache.lucene.search.highlight.Highlighter.getBestTextFragments(Highlighter.java:197)
        at org.elasticsearch.search.highlight.PlainHighlighter.highlight(PlainHighlighter.java:119)
        ... 9 more
Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 173493
        at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284)
        at org.apache.lucene.index.memory.MemoryIndex.addField(MemoryIndex.java:467)
        ... 19 more
```
I thought this was fixed in #9881 - but for some reason ES is still trying to highlight message.raw which is not_analyzed. The comment in the Kibana issue https://github.com/elastic/kibana/issues/2782#issuecomment-105224019 says that long terms shouldn't get into the index and not_analyzed should be skipped - but neither seem to be happening here.

Reproduction in this [gist](https://gist.github.com/jimmyjones2/0be6664a471a30b2e624) then add index to Kibana and in discover search for "execute". My original setup involves Elasticsearch sending its own logs to logstash via log4j socket, then ingesting into another elasticsearch instance - can include details here if needed.

**Comment by clintongormley** [comment]
Thanks for reporting @jimmyjones2 

@brwe please can you investigate?

**Comment by brwe** [comment]
Indeed, the problem was not fixed on 1.x branch. Two things happened: 1) the test I wrote for the huge terms actually did not trigger the exception on 1.x because on 1.x this only happens with certain queries like prefix query but not match query (which I use in the test) and 2) I fixed the issue by catching a MaxBytesLengthExceededException in PlainHighlighter but on 1.x this is actually wrapped in a RuntimeException. So this did not fix it on 1.x but the tests passed anyway. I made a pull request to change this now here #11683. Sorry.

**Comment by jimmyjones2** [comment]
@brwe Thanks! Might this fix get into 1.6.1?

**Comment by Filirom1** [comment]
+1

**Comment by brwe** [comment]
I pushed to 1.6 and 1.x branch, the fix will be in 1.6.1. Thanks again for reporting!

**Comment by asatsi** [comment]
+1 simple searches not happening due to this when using with ELK :-( Kind of annoying and frustrating.

**Comment by Filirom1** [comment]
Thanks, it works like a charm now :beers:

**Comment by tmartensen** [comment]
This still doesn't work for me when using Kibana 4.1.1 and Elasticsearch 1.7.1. Is there something else that needs to be done to existing indexes?

**Comment by clintongormley** [comment]
@tmartensen you shouldn't have to do anything, as long as we're talking about the same exception.  More details?

**Comment by tmartensen** [comment]
I'm still getting the same exception after upgrading to 1.7.1. I'm trying to log SOAP messages that are larger than normal, but not outrageously large, as seen bellow by filtering on the `org.springframework.ws.client.messagetracing*` logger name, and by a custom class that has much shorter messages.

```
Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: [logstash-2015.08.26][4]: query[filtered(logger_name:org.springframework.ws.client.messagetracing* logger_name:com.xxx.xxx.xxx)->BooleanFilter(+QueryWrapperFilter(ConstantScore(*:*)) +cache(@timestamp:[1440306000000 TO 1440777217294]))],from[0],size[500],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@2f9f7c14>!]: Fetch Failed [Failed to highlight field [message.raw]]
	at org.elasticsearch.search.highlight.PlainHighlighter.highlight(PlainHighlighter.java:126)
	at org.elasticsearch.search.highlight.HighlightPhase.hitExecute(HighlightPhase.java:128)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:192)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:501)
	at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:868)
	at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:862)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 47034
```

**Comment by jimmyjones2** [comment]
Fix worked for me, after remembering to upgrade the client node

**Comment by tmartensen** [comment]
@jimmyjones2 what does that entail? I've upgraded the index through the upgrade API for the offending indexes.

**Comment by clintongormley** [comment]
It means: make sure you upgrade all Elasticsearch nodes, including the client nodes (if you're using them)

**Comment by tmartensen** [comment]
I see. I'm using ES unclustered at the moment, straight out of the box.
