### ISSUE TITLE
Provide online Javadocs

### ISSUE THREAD

**Issue by brusic** [elastic/elasticsearch#1203]
A hosted version of the Javadocs will greatly help out on the mailing-list/forum when trying to point out a class/method to someone.  The online documentation is great for illustrating concepts, but something at the class level would also help

**Comment by joschi** [comment]
Publishing the Javadoc artifacts on Maven Central along with the main artifacts would enable services like [Javadoc.io](http://www.javadoc.io/) to be used and to view the Elasticsearch Javadoc online: http://www.javadoc.io/doc/org.elasticsearch/elasticsearch/1.7.3

**Comment by joschi** [comment]
@drewr Are there any plans to start publishing the Javadoc artifacts of Elasticsearch on Maven Central again?

**Comment by digitalrinaldo** [comment]
What is the status of java doc support? Can you consider adding a second download link with each release that includes the javadocs. I can trivially go produce the docs and put them up myself but do we really need everyone to publish the java docs. Are you aware that tools like Eclipse and Netbeans have built in support for java docs and that the entire code recommender support and refactoring doesn't work well with Javadocs and that at any point in time a developer may have multiple versions of Elasticsearch so having all the javadocs versioned to match the sources is needed for serious developers.

**Comment by mrburrito** [comment]
+1 for publishing these on an official ES site and linking to them. The API guide is pretty sparse and refers back to the DSL documentation which is somewhat more useful. It would be extremely useful to have a hyperlinked API docset to browse. I'm really surprised you don't have these published already since it's a rather trivial addition to your build process. Also, I thought building the docs was a requirement for publishing to Maven central so it should just be a matter of putting them on the site and linking. Please do so for all tagged versions.

**Comment by seralf** [comment]
Furthermore, if somebody generates javadocs for his/her project, which uses ES as dependency, the javadocs can be linked to provide an easier navigation. 

Ideally it would be great to be able to use something like:

```

<build>
...
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-javadoc-plugin</artifactId>
	<configuration>
		...		
		<links>
			<link>https://.../javadoc/elasticsearch/api/index.html</link>
		</links>
	</configuration>
	...
</plugin>
...
</build>
```

in the POM of our Java project, which uses ES.

**Comment by fbacchella** [comment]
4 years old very very simple ticket and still not closed ?

**Comment by vruchtvet** [comment]
should we use elasticsearch when proper documentation is missing??

**Comment by brusic** [comment]
The documentation is there, just not simply available on a publicly available site. You can always create your own Javadocs from the source.

**Comment by hossmaa** [comment]
Sorry, but this is really unacceptable from a piece of software of Elasticsearch's caliber!

**Comment by fbacchella** [comment]
@brusic is that a joke ? That's not a serious answer.

**Comment by s1monw** [comment]
folks, please keep calm here. At the time this issue was opened there was literally no javadoc on elasticsearch. Now we are in a much better situation along those lines and I think we all agree we should do it and at least publish it with the zip/tar files as a start. It's a rather low hanging fruit but no reason to get angry either.

**Comment by brusic** [comment]
I am the one that created this issue over 4 years ago, so I understand the importance. Lack of publicly accessible Javadocs is by no means a show-stopper. You can still create them locally since the actual code does contain excellent Javadoc standards.

Elastic at one point was creating Javadocs, just not linking to them:
http://jenkins.elasticsearch.org/job/Elasticsearch%20Master%20Branch%20Javadoc/Elasticsearch_API_Documentation/

The current Jenkins infrastructure is building Javadocs only for the latest 1.7 branch:
http://build-us-00.elastic.co/job/ES%20Javadocs/ws/target/site/apidocs/index.html

**Comment by mrburrito** [comment]
@brusic the fact that this issue has been open for 4 years is a bit ridiculous in and of itself. @s1monw, you just mentioned that it's low hanging fruit; in theory it's been low hanging fruit for at least 4 years. I for one am not angry (I've been using the REST API, not the Java libraries, in my current project), but definitely disappointed. Honestly, I'm surprised you were able to publish to Maven Central without them since Sonatype is pretty strict about that requirement! Hopefully this issue is resolved soon and everyone is happy.

**Comment by brusic** [comment]
Back when I created this issue, it was what I label as Elasticsearch the project, not Elastic the company. Big difference! :) Just Shay working on an open-source project. I believe Shay had neither the time nor the infrastructure initially, and since this issue is old, it never was focused on after the creation of the company (my assumption). Do not judge an issue on its age, if it was created "in the old days".

Things have changed since then and they do have the capacity to create Javadocs as part of the build process. Until recently, they were creating online Javadocs (see my links above), just not telling anyone about them. It looks like they changed the Jenkins build and the Javadoc process was left behind.

Things could be worse: Lucene has Javadocs, but no real documentation (sorry Lucene committers, it sucks). What little documentation there is is embedded in the Javadocs.

It appears this issue on the roadmap (albeit potentially distant), and I feel comments at this point should be useful ones such as pointers and tips.

**Comment by p0lar** [comment]
@brusic @s1monw There **are** actually Javadocs available on a publicly available server. If you google on this, you will be directed there. Since there is no official hosting yet (the results from the linked jenkins ci is not what I would expect as sustained hosting), I will continue to host these docs.

**Comment by fbacchella** [comment]
Just build javadoc in the pom and provides them as artifact and then upload them to maven repositories. IDE like Eclipse will then be able to use it.

**Comment by rjernst** [comment]
> Just build javadoc in the pom and provides them as artifact and then upload them to maven repositories. IDE like Eclipse will then be able to use it.

We are already doing this in 2.x and master. In 2.x it actually only happens for the "release" maven profile (not sure why, never noticed that before), but in gradle it happens simply with the standard assemble task.

**Comment by fbacchella** [comment]
But there are not available to download in maven repositories, so Eclipse can't use them :
see at 
http://mavensearch.io/repo/org.elasticsearch/elasticsearch-transport-thrift/2.7.0
http://mavensearch.io/repo/org.elasticsearch/elasticsearch/2.2.0

**Comment by rjernst** [comment]
@fbacchella They are already available for 5.0 snapshots:
https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch/5.0.0-SNAPSHOT/

I had also thought 2.x was generating javadocs after #14935, but found it wasn't because it was hidden under a "release" profile. I've fixed that in fc03a1a to always produce javadocs now, so we should start seeing them in 2.3 snapshots.

**Comment by joschi** [comment]
Javadocs have been published for Elasticsearch 2.3.0:
* https://search.maven.org/#artifactdetails%7Corg.elasticsearch%7Celasticsearch%7C2.3.0%7Cjar
* https://www.javadoc.io/doc/org.elasticsearch/elasticsearch/2.3.0

I think this issue can be closed.

**Comment by dadoonet** [comment]
Agreed. Thanks.

**Comment by p0lar** [comment]
@joschi @dadoonet  Javadocs prior to 2.3.0 are still missing on that page.
