### ISSUE TITLE
Bats tests should use plugins built in the elasticsearch repository

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12651]
The bats tests currently install watcher to test installing plugins. It should really install one of the plugins built by the elasticsearch repository. Watcher can test itself. This will also solve the issue of not being able to run the tests properly when there isn't a watcher plugin available for the version of elasticsearch we're building. There will always be an appropriate version of the locally built plugins around because we build it as part of the build.

**Comment by tlrx** [comment]
Sounds like a good idea!

**Comment by nik9000** [comment]
I'm so going to do this once we merge https://github.com/elastic/elasticsearch/pull/12646

**Comment by jaymode** [comment]
I like this idea, but do we have a plugin in this repository that has a `bin` and `config` dir inside it? I think some of the tests look for that so we may need to add a test one with those directories or something

**Comment by uboness** [comment]
+1 on ditching watcher... and +1 on a plugin with `config` and `bin` dirs

**Comment by dadoonet** [comment]
I guess we can add that to the jvm example plugin: https://github.com/elastic/elasticsearch/tree/master/plugins/jvm-example
?

**Comment by nik9000** [comment]
> I like this idea, but do we have a plugin in this repository that has a bin and config dir inside it? I think some of the tests look for that so we may need to add a test one with those directories or something

I've already started....

**Comment by nik9000** [comment]
https://github.com/elastic/elasticsearch/pull/12787

**Comment by nik9000** [comment]
Ok! All done. The tests all use the jvm-example plugin and no longer try to use watcher. They deserve some more refactoring and we should really be installing all the plugins to make sure they make it. But I'll do that under #12717.

**Comment by nik9000** [comment]
Silly closed icon! I didn't reject this issue! I fixed it in four different pull requests!

**Comment by dadoonet** [comment]
@nik9000 Why did not you push your change to 2.0 branch? On purpose?
cc @clintongormley

**Comment by nik9000** [comment]
> @nik9000 Why did not you push your change to 2.0 branch? On purpose?

Do we need it in 2.0? I was going by the mantra of "don't push anything we don't need there". I think I have quite a few bats changes just in master that aren't in 2.0 yet. I can push them if you think its important. For the most part it'd probably work just fine to test 2.0-beta-whatever changes by staging them in the testroot or changing the elasticsearch.verion in master.

**Comment by dadoonet** [comment]
I don't know. While merging some of my PR from master to 2.0 branch, I just discovered that was not merge and that 2.0 branch still wants to install shield for vagrant tests.

Not a big deal to me. Was just asking if it was intentional not to merge it or just that you forgot :)
