### ISSUE TITLE
Deadlock in log4j2 RollingFileAppender during log rollover on ingest attachment nodes

### ISSUE THREAD

**Issue by Rassyan** [elastic/elasticsearch#131404]
### Elasticsearch Version

8.16.1

### Java Version

_bundled_

### OS Version

-

#### Summary

The issue observed here is exactly the same as in #91964 and remains unresolved.  There is a reproducible Java-level deadlock in Elasticsearch ingest attachment nodes during log rollover. This deadlock causes ingest nodes to hang indefinitely, and is especially likely to occur under heavy ingest/logging load.  After reviewing #93878 discussions, it is clear that the community has focused on logging loss, logging bridges, and permission issues related to log4j, but has not identified or addressed the potential for a JVM-level deadlock caused by log4j2's RollingFileManager and BufferedWriter lock cycle.

#### Details

- **Elasticsearch version:** 8.16.1
- **log4j2 version:** 2.19.0 (bundled)
- **Node type:** Dedicated ingest node

#### jstack evidence

Below is a minimal excerpt from a real production jstack, showing the deadlock:

```
Found one Java-level deadlock:
=============================
"elasticsearch[1751529376016684232][cluster_coordination][T#1]":
  waiting to lock monitor 0x00007f3f214190e0 (object 0x00000010012ae8f0, a org.apache.logging.log4j.core.appender.rolling.RollingFileManager),
  which is held by "elasticsearch[1751529376016684232][write][T#16]"

"elasticsearch[1751529376016684232][write][T#16]":
  waiting to lock monitor 0x00007f3f02e4a000 (object 0x0000001011305730, a java.io.BufferedWriter),
  which is held by "elasticsearch[1751529376016684232][write][T#15]"

"elasticsearch[1751529376016684232][write][T#15]":
  waiting to lock monitor 0x00007f3f214190e0 (object 0x00000010012ae8f0, a org.apache.logging.log4j.core.appender.rolling.RollingFileManager),
  which is held by "elasticsearch[1751529376016684232][write][T#16]"
```

#### Impact

- Ingest nodes become permanently stuck, requiring a process restart.
- All ingest pipelines and possibly cluster coordination are affected.

#### Attachments

- Full jstack available upon request.

### Steps to Reproduce

1. Use attachment processor
2. Almost always during log rollover under ingest load

As https://github.com/elastic/elasticsearch/pull/93878#issuecomment-1433884689 said

### Logs (if relevant)

[jstack.txt](https://github.com/user-attachments/files/21277973/jstack.txt)

**Comment by Rassyan** [comment]
@joegallo @masseyke , since you have participated in related discussions before, could you please take a look at this new issue? Your input would be greatly appreciated. Thank you!

**Comment by masseyke** [comment]
@Rassyan is there any chance that you have tika logging enabled in your elasticsearch config? It's been a long time since I've looked at this, but it seems like that was the one remaining potential source of problems that we were aware of. I saw a very similar deadlock a while back. It only happened if I had log4j 2.18.0 or newer and had tika logging enabled (it's off by default in elasticsearch, unless someone has changed that recently). Here's what I saw:
```
Found one Java-level deadlock:
=============================
"elasticsearch[keiths-mbp.lan][masterService#updateTask][T#1]":
  waiting to lock monitor 0x0000600005bbd930 (object 0x000000175b341a08, a org.apache.logging.log4j.core.appender.rolling.RollingFileManager),
  which is held by "elasticsearch[keiths-mbp.lan][write][T#15]"

"elasticsearch[keiths-mbp.lan][write][T#15]":
  waiting to lock monitor 0x0000600005bd0000 (object 0x000000175b82a3d8, a java.io.BufferedWriter),
  which is held by "elasticsearch[keiths-mbp.lan][write][T#1]"

"elasticsearch[keiths-mbp.lan][write][T#1]":
  waiting to lock monitor 0x0000600005bcf810 (object 0x000000175b828358, a java.io.PrintStream),
  which is held by "elasticsearch[keiths-mbp.lan][write][T#15]"
```

**Comment by masseyke** [comment]
I think that this is a log4j bug, and I think that it only happens if `appender.rolling.strategy.fileIndex` is set to `nomax` (which is what elasticsearch does) and if rollover is happening very frequently (which it is, if tika logging is enabled). If I can get it into a reproducible test, I'll open a log4j bug. I have not tested this, but I think you could avoid this if you either disabled tika-related logging (the settings in https://github.com/elastic/elasticsearch/blob/main/modules/ingest-attachment/src/main/config/log4j2.properties) or increase your log rollover size.

**Comment by masseyke** [comment]
It looks like this deadlock also requires that a call to System.getEnv() throw a SecurityException. Unfortunately that is not possible in the current JDK (the security manager has been removed). So I can't create a test case to reproduce this on Java 21+. But the good news is that this also means that this deadlock can't occur on newer versions of Elasticsearch that run on versions of Java that don't have the security manager.

**Comment by Rassyan** [comment]
> [@Rassyan](https://github.com/Rassyan) is there any chance that you have tika logging enabled in your elasticsearch config? It's been a long time since I've looked at this, but it seems like that was the one remaining potential source of problems that we were aware of. I saw a very similar deadlock a while back. It only happened if I had log4j 2.18.0 or newer and had tika logging enabled (it's off by default in elasticsearch, unless someone has changed that recently). Here's what I saw:
> 
> ```
> Found one Java-level deadlock:
> =============================
> "elasticsearch[keiths-mbp.lan][masterService#updateTask][T#1]":
>   waiting to lock monitor 0x0000600005bbd930 (object 0x000000175b341a08, a org.apache.logging.log4j.core.appender.rolling.RollingFileManager),
>   which is held by "elasticsearch[keiths-mbp.lan][write][T#15]"
> 
> "elasticsearch[keiths-mbp.lan][write][T#15]":
>   waiting to lock monitor 0x0000600005bd0000 (object 0x000000175b82a3d8, a java.io.BufferedWriter),
>   which is held by "elasticsearch[keiths-mbp.lan][write][T#1]"
> 
> "elasticsearch[keiths-mbp.lan][write][T#1]":
>   waiting to lock monitor 0x0000600005bcf810 (object 0x000000175b828358, a java.io.PrintStream),
>   which is held by "elasticsearch[keiths-mbp.lan][write][T#15]"
> ```

Never changed. Same as changes of https://github.com/elastic/elasticsearch/pull/93878
```
logger.org_apache_pdfbox.name = org.apache.pdfbox
logger.org_apache_pdfbox.level = off

logger.org_apache_poi.name = org.apache.poi
logger.org_apache_poi.level = off

logger.org_apache_fontbox.name = org.apache.fontbox
logger.org_apache_fontbox.level = off

logger.org_apache_xmlbeans.name = org.apache.xmlbeans
logger.org_apache_xmlbeans.level = off
```

[log4j2.properties.txt](https://github.com/user-attachments/files/21309177/log4j2.properties.txt)

**Comment by Rassyan** [comment]
@masseyke Thank you for your detailed analysis. To help investigate the logging deadlock, we’ve verified the following:  

- Log files **failed to roll over** during deadlock (confirmed via `logs/` directory state)  
- Zero new logs generated after deadlock occurred  
- Java version: **openjdk 21.0.1 2023-11-02 LTS**  
- Log4j version: **2.19.0** (bundled with Elasticsearch 8.16.1)  
- ​Deadlock Path Confirmed: The log snippet shows the critical sequence: `System.getenv() → SecurityException → Log4j debug logging → RollingFileManager.rollover()`
- POI Component's Role: While Tika logging is disabled, we observe frequent org.apache.poi.hdgf.chunks.Chunk warnings during document parsing. These likely accelerated log growth and rollover triggers.

**Comment by Rassyan** [comment]
> It looks like this deadlock also requires that a call to System.getEnv() throw a SecurityException. Unfortunately that is not possible in the current JDK (the security manager has been removed). So I can't create a test case to reproduce this on Java 21+. But the good news is that this also means that this deadlock can't occur on newer versions of Elasticsearch that run on versions of Java that don't have the security manager.

We've confirmed the deadlock occurs in our JDK 21 environment (Openjdk 21.0.1) because **SecurityManager remains active** despite JEP 411 - Elasticsearch explicitly enables it before v8.19 (#127727)

The deadlock flow seems like:
```mermaid
graph TD
    ThreadA[Thread A: Log Roller] -->|Holds| LockA[RollingFileManager Lock]
    ThreadB[Thread B: Log Writer] -->|Holds| LockB
    ThreadA -->|Triggers| SecurityException
    SecurityException -->|Requires logging| DebugLog[Debug Log]
    DebugLog -->|Waits for| LockB[BufferedWriter Lock]
    
    ThreadB -->|Reaches threshold| NeedRollover[Needs Rollover]
    NeedRollover -->|Waits for| LockA
```
Hope https://github.com/elastic/elasticsearch/pull/93878#issuecomment-1433884689 can help you reproduce.

**Comment by masseyke** [comment]
Thanks. I was able to reproduce it (or something very close), and have started a log4j discussion at https://github.com/apache/logging-log4j2/discussions/3837. In the meantime, does disabling poi and pdfbox logging avoid the problem for you?

**Comment by Rassyan** [comment]
Thanks for investigating this. Disabling POI/PDFBox logging didn't fix the issue.  
Actually I'm puzzled why this deadlock occurs in 8.x but never in 7.x despite identical Log4j usage patterns. Potential factors:  
   - ES 8.x uses Log4j 2.18+ (where the deadlock was introduced)  
   - ES 7.x didn't require `-Djava.security.manager=allow`  
   - Different JDK thread scheduling behaviors (we've reproduced on JDK 21)  

Looking forward to your insights.

**Comment by masseyke** [comment]
I believe in previous testing I found that the issue began with logatash 2.18.0 (although it's been a while since I checked that and I'm working from memory). That wasn't used until some point in the elasticsearch 8.x lifecycle.
It would probably be useful to check what is filling up your logs. Maybe some other tika component is logging heavily and triggering this? Or maybe you have an unusually small rollover size?

**Comment by Rassyan** [comment]
Here's the log sequence showing the deadlock trigger with observations:

Before the SecurityException, we see repeated POI warnings like:
```
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk] Command offset 19 past end of data at 3
```
This happens despite having `logger.org_apache_poi.level = off` even `logger.chunk.level = off` in our configuration, suggesting the attachment processor might bypass logging controls during document parsing.

The SecurityException then appears:
```
[2025-07-15T12:21:02,341][WARN ][stderr] The system environment variables are not available to Log4j due to security restrictions
```
This triggers Log4j's debug handling during rollover, creating the lock cycle as shown in the full stack trace. The logs clearly demonstrate the deadlock pathway from SecurityException through Log4j's nested locks.

Our configuration uses the default 128MB rollover size, which should reasonably limit rollover frequency under normal conditions. However, as shown in the logs, the POI component generates warning logs at an extremely high rate during document parsing. 

Here is the complete log snippet:
```
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 19 past end of data at 3
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 19 past end of data at 3
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 19 past end of data at 3
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 22 past end of data at 3
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 39 past end of data at 20
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 67 past end of data at 48
[2025-07-15T12:21:02,338][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 67 past end of data at 48
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,338][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 67 past end of data at 48
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 67 past end of data at 48
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 67 past end of data at 48
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 67 past end of data at 48
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 142 past end of data at 134
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 26 past end of data at 7
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 26 past end of data at 7
[2025-07-15T12:21:02,339][INFO ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command of type 31 not processed!
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 50 past end of data at 35
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 50 past end of data at 35
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 50 past end of data at 35
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 50 past end of data at 35
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 50 past end of data at 35
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 50 past end of data at 35
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 50 past end of data at 35
[2025-07-15T12:21:02,339][WARN ][o.a.p.h.c.Chunk          ] [1751529376016684232] Command offset 51 past end of data at 35
[2025-07-15T12:21:02,341][WARN ][stderr                   ] [1751529376016684232] The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
[2025-07-15T12:21:02,341][WARN ][stderr                   ] [1751529376016684232] java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
[2025-07-15T12:21:02,341][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:488)
[2025-07-15T12:21:02,341][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.security.AccessController.checkPermission(AccessController.java:1071)
[2025-07-15T12:21:02,341][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
[2025-07-15T12:21:02,341][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.lang.System.getenv(System.java:1203)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.EnvironmentPropertySource.containsProperty(EnvironmentPropertySource.java:101)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil$Environment.get(PropertiesUtil.java:533)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil$Environment.access$200(PropertiesUtil.java:444)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil.getStringProperty(PropertiesUtil.java:392)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil.getBooleanProperty(PropertiesUtil.java:179)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isDebugPropertyEnabled(StatusLogger.java:143)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:426)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:327)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1982)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:740)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:61)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.appenderErrorHandlerMessage(AppenderControl.java:118)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.isRecursiveCall(AppenderControl.java:110)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.shouldSkip(AppenderControl.java:93)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:86)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.Logger.log(Logger.java:162)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1652)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.logging.LoggingOutputStream.log(LoggingOutputStream.java:109)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.logging.LoggingOutputStream.flush(LoggingOutputStream.java:94)
[2025-07-15T12:21:02,342][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.logging.LoggingOutputStream.write(LoggingOutputStream.java:59)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.OutputStream.write(OutputStream.java:167)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintStream.implWrite(PrintStream.java:643)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintStream.write(PrintStream.java:623)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:309)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:405)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:410)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:214)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:201)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:262)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.BufferedWriter.implFlush(BufferedWriter.java:372)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:359)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintWriter.implNewLine(PrintWriter.java:659)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintWriter.newLine(PrintWriter.java:649)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintWriter.println(PrintWriter.java:808)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintWriter.println(PrintWriter.java:1006)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.LowLevelLogUtil.log(LowLevelLogUtil.java:44)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.LowLevelLogUtil.logException(LowLevelLogUtil.java:55)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.EnvironmentPropertySource.logException(EnvironmentPropertySource.java:43)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.EnvironmentPropertySource.containsProperty(EnvironmentPropertySource.java:103)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil$Environment.get(PropertiesUtil.java:533)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil$Environment.access$200(PropertiesUtil.java:444)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil.getStringProperty(PropertiesUtil.java:392)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil.getBooleanProperty(PropertiesUtil.java:179)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isDebugPropertyEnabled(StatusLogger.java:143)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:426)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:327)
[2025-07-15T12:21:02,343][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1982)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:740)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:61)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.appenderErrorHandlerMessage(AppenderControl.java:118)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.isRecursiveCall(AppenderControl.java:110)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.shouldSkip(AppenderControl.java:93)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:86)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrate
gy.java:82)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.Logger.log(Logger.java:162)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1652)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.logging.LoggingOutputStream.log(LoggingOutputStream.java:109)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.logging.LoggingOutputStream.flush(LoggingOutputStream.java:94)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.logging.LoggingOutputStream.write(LoggingOutputStream.java:59)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.OutputStream.write(OutputStream.java:167)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintStream.implWrite(PrintStream.java:643)
[2025-07-15T12:21:02,346][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintStream.write(PrintStream.java:623)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:309)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:405)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:410)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:214)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:201)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:262)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.BufferedWriter.implFlush(BufferedWriter.java:372)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:359)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintWriter.implNewLine(PrintWriter.java:659)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintWriter.newLine(PrintWriter.java:649)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintWriter.println(PrintWriter.java:808)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.io.PrintWriter.println(PrintWriter.java:1006)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.LowLevelLogUtil.log(LowLevelLogUtil.java:44)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.LowLevelLogUtil.logException(LowLevelLogUtil.java:55)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.EnvironmentPropertySource.logException(EnvironmentPropertySource.java:43)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.EnvironmentPropertySource.containsProperty(EnvironmentPropertySource.java:103)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil$Environment.get(PropertiesUtil.java:533)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil$Environment.access$200(PropertiesUtil.java:444)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil.getStringProperty(PropertiesUtil.java:392)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.util.PropertiesUtil.getBooleanProperty(PropertiesUtil.java:179)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isDebugPropertyEnabled(StatusLogger.java:143)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:426)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.status.StatusLogger.isEnabled(StatusLogger.java:354)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1914)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:463)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.rolling.PatternProcessor.formatFileName(PatternProcessor.java:291)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.rolling.PatternProcessor.formatFileName(PatternProcessor.java:278)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.rolling.AbstractRolloverStrategy.getEligibleFiles(AbstractRolloverStrategy.java:94)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.rolling.AbstractRolloverStrategy.getEligibleFiles(AbstractRolloverStrategy.java:87)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy.rollover(DefaultRolloverStrategy.java:524)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.rolling.RollingFileManager.rollover(RollingFileManager.java:504)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.rolling.RollingFileManager.rollover(RollingFileManager.java:394)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.rolling.RollingFileManager.checkRollover(RollingFileManager.java:308)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:300)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:674)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
[2025-07-15T12:21:02,347][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:674)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:674)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j.core@8.16.1/org.apache.logging.log4j.core.Logger.log(Logger.java:162)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2106)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.internal.DefaultLogBuilder.logMessage(DefaultLogBuilder.java:241)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.internal.DefaultLogBuilder.log(DefaultLogBuilder.java:169)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.poi.hdgf.chunks.Chunk.processCommands(Chunk.java:184)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.poi.hdgf.chunks.ChunkFactory.createChunk(ChunkFactory.java:207)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.poi.hdgf.streams.ChunkStream.findChunks(ChunkStream.java:66)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.poi.hdgf.streams.PointerContainingStream.findChildren(PointerContainingStream.java:87)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.poi.hdgf.streams.PointerContainingStream.findChildren(PointerContainingStream.java:94)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.poi.hdgf.streams.PointerContainingStream.findChildren(PointerContainingStream.java:67)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.poi.hdgf.HDGFDiagram.<init>(HDGFDiagram.java:92)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.poi.hdgf.extractor.VisioTextExtractor.<init>(VisioTextExtractor.java:52)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:244)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:183)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:203)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:71)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:109)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.extractor.EmbeddedDocumentUtil.parseEmbedded(EmbeddedDocumentUtil.java:240)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.parseEmbedded(AbstractPOIFSExtractor.java:388)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.handleEmbeddedOfficeDoc(AbstractPOIFSExtractor.java:223)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.handleEmbeddedOfficeDoc(AbstractPOIFSExtractor.java:156)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.microsoft.WordExtractor.parse(WordExtractor.java:227)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:230)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:183)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:203)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.apache.tika.Tika.parseToString(Tika.java:525)
[2025-07-15T12:21:02,348][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.ingest.attachment.TikaImpl.lambda$parse$0(TikaImpl.java:98)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.ingest.attachment.TikaImpl.parse(TikaImpl.java:97)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.ingest.attachment.AttachmentProcessor.execute(AttachmentProcessor.java:122)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:171)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:132)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.ConditionalProcessor.execute(ConditionalProcessor.java:102)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:171)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:146)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:130)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.IngestDocument.executePipeline(IngestDocument.java:850)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.IngestService.executePipeline(IngestService.java:1119)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.IngestService.executePipelines(IngestService.java:971)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.ingest.IngestService$1.doRun(IngestService.java:842)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at org.elasticsearch.server@8.16.1/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232]       at java.base/java.lang.Thread.run(Thread.java:1583)
[2025-07-15T12:21:02,349][WARN ][stderr                   ] [1751529376016684232] The system environment variables are not available to Log4j due to security restrictions: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getenv.*")
```

**Comment by masseyke** [comment]
It looks like this has been fixed in newer versions of log4j. I just created https://github.com/elastic/elasticsearch/issues/132035 to update our log4j version.

**Comment by mosche** [comment]
Unfortunately the log4j update is currently blocked by some dependency issues. We're working on resolving these.

@masseyke I'm wondering how complex the reproduction is / was? Despite being still present on 8.18, the Java Security Manager is not "active" anymore. If simple enough, could you verify the problem doesn't exist on 8.18 anymore?

**Comment by masseyke** [comment]
Check out https://github.com/apache/logging-log4j2/discussions/3837#discussion-8601160. The only security-manager-related requirement is that you need System.getenv() configured to throw a SecurityException. I think that entitlements still do that but I haven't tested. If so, I think if you just turn on tika/poi logging, and ingest a lot of data through the ingest attachment processor, you'll still hit this.

**Comment by mosche** [comment]
> I think that entitlements still do that but I haven't tested.
No, this won't be the case for entitlements.

I haven't found any attachment triggering poi logging to be honest. If you have a collection of pdfs that do, please reach out.
