### ISSUE TITLE
Shards out of sync when setting  refresh_interval & number_of_replicas at the same time

### ISSUE THREAD

**Issue by msimos** [elastic/elasticsearch#14319]
If you create an index number_of_replicas to 0 and refresh_interval to -1 (using one API call) & add some documents. Then set number_number_of_replicas to 1 and refresh_interval to "1s" and add some more documents. The primary and replicas are out of sync, it looks like the replica doesn't have the new documents. See this gist for a repro:

https://gist.github.com/msimos/869292265208852fbee4

If you run the match_all query multiple times you'll see the different documents returned. If you use preference=_primary then all documents are returned. If the query hits the replica, then only the first documents are returned when replicas were set to 0. Also using _cat/shards you can see the size difference between the shards.

It seems you can workaround this by doing sending this in two separate calls:

```
PUT /index/_settings
{
  "number_of_replicas": 1
}

PUT /index/_settings
{
  "refresh_interval": "1s"
}
```
Also seems the ordering matters, that "number_of_replicas": 1 is set before "refresh_interval": "1s". This was on Elasticsearch 1.7.2.

**Comment by clintongormley** [comment]
Hi @msimos 

Thanks for the report and the nice clear recreation.  It is not that the shards are out of sync, but that the shard holding the first doc thinks that it doesn't need to refresh.

This is fixed in 2.0 already

**Comment by mikemccand** [comment]
A forced refresh (``/index2/_refresh``) resolves the issue, so somehow the replica is failing to refresh after 1s (but did in fact index the 2nd document).

Curiously, if I pass ``"number_of_shards": 1`` when creating the index, the bug doesn't happen, but with 2 shards, it does.  Hmm.

**Comment by mikemccand** [comment]
OK I think I see what's happening:

The new replica is created (because of ``"number_of_replicas": 1``), but because this is async change, the additional ``"refresh_interval": "1s"`` in the same request is never applied to the newly created replica shards since they have not yet set up listeners (``IndexShard.ApplyRefreshSettings``) for settings changes.

So the replica shards still have the old ``refresh_interval`` (-1).

Reversing the two settings works because the newly created replica shards will inherit the latest index settings when they are created, including the change just made to ``refresh_interval``.

I'm not sure how to cleanly fix this. @bleskes?

Maybe we could simply move ``number_of_replicas`` to the end of all settings updated in one request?

**Comment by s1monw** [comment]
@mikemccand can you try and verify if that still happens on master / 3.0?

**Comment by mikemccand** [comment]
@s1monw I'll test master.  @clintongormley already checked that 2.0 fixes it (I'm not sure why/how!) ...

**Comment by mikemccand** [comment]
@s1monw master doesn't have the bug either ... I'm not sure why.

**Comment by bleskes** [comment]
I did some digging and this has to do with the fact that index shards are created with old index settings. IndexShard get's it's index setting using guice and the `@IndexSettings` annotation. This is supposed be supplied by [IndexSettingsProvider](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/index/settings/IndexSettingsProvider.java) , which in turn asks `IndexSettingsService` for the latest setting. For some unknown reason, Guice decides to cache those settings and thus IndexShard gets a stale copy. This means that if Guice capture and old settings, the settings are changed and then a shard is created, the shard will see the old setting. It does register a setting change listener but as far as `IndexSettingService` is concerned, no settings have changed since the last iteration. This doesn't happen in 2.0 because we don't inject the index setting to the shard anymore but rather ask for a live copy in the IndexShard constructor. Master is of course totally rewritten to another mechanism.

I've put a test reproducing on https://gist.github.com/bleskes/1e336a206a52cb4f1b0f . (based on 1.7 code)

I think we can do one of the following:
- Fix the Guice issue and make the provider be called every time (I did some looking and this looks like a rabbity hole - unless some knows what needs to be done)
- Change 1.7 to do what 2.0 does and not inject the index setting to the IndexShard. This is a local fix and we might suffer other simillar issues in the future, so if we go down this right I suggest we remove the index settings annotation and use this mechanism all over the place (in 2.x and 1.7).

Thoughts?

**Comment by mikemccand** [comment]
Option 1 sounds scary (I don't like rabbit holes).  Option 2 seems like a biggish change to make on a bug fix branch?  We could simply leave this bug unfixed in 1.x and encourage users who hit it to upgrade to 2.x?

**Comment by jasontedor** [comment]
> We could simply leave this bug unfixed in 1.x and encourage users who hit it to upgrade to 2.x?

Since a workaround exists in the 1.x line, this seems to me to be a sensible option.

**Comment by bleskes** [comment]
note that the work around is likely to to work but not guaranteed. Sometime shard creation is throttled/disabled (see test) and  then it doesn't.

There is the option of just doing the on liner change in 1.7 to make index shard get a new setting every time and only the bigger change (i.e., remove the provider and the annotation) in 2.x .

**Comment by s1monw** [comment]
> @s1monw master doesn't have the bug either ... I'm not sure why.

@mikemccand in master I trashed this Provider @bleskes is talking about entirely. New shards are guaranteed to see the latest settings.

**Comment by bleskes** [comment]
Unless someone objects soon, I'll assume we're going with:

1) One line fix to index shard in 1.7 to have an injected index settings.
2) removal of the provider in 2.x.

**Comment by jasontedor** [comment]
> Unless someone objects soon, I'll assume we're going with:

>1) One line fix to index shard in 1.7 to have an injected index settings.
2) removal of the provider in 2.x.

+1

**Comment by mikemccand** [comment]
> @mikemccand in master I trashed this Provider @bleskes is talking about entirely. 

OK wonderful!

> Unless someone objects soon, I'll assume we're going with:
> 
> 1) One line fix to index shard in 1.7 to not have an injected index settings.
> 2) removal of the provider in 2.x.

+1

**Comment by danielmitterdorfer** [comment]
I've implemented the fix for 1.7 (see PR #14522). I am about to work on removing the provider in 2.x.

**Comment by jasontedor** [comment]
This was closed by #14522.
