### ISSUE TITLE
gradle build fails on ibm jdk

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14710]
```
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version : 2.8
  JDK Version    : pxa6480sr1-20150417_01 (SR1) (IBM Corporation)
  OS Info        : Linux 4.2.0-16-generic (amd64)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/rmuir/workspace/elasticsearch/core/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':core'.
> Failed to apply plugin [id 'elasticsearch.build']
   > Cannot invoke method contains() on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':core'.
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
    at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:153)
    at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
    at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
    at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:499)
    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
    at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
    at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'elasticsearch.build']
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
    at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:35)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:79)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:135)
    at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
    at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
    at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
    at org.gradle.api.Script$apply.callCurrent(Unknown Source)
    at build_a1fw0t7njqucp7ny71abi508r.run(/home/rmuir/workspace/elasticsearch/core/build.gradle:24)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
    ... 47 more
Caused by: java.lang.NullPointerException: Cannot invoke method contains() on null object
    at org.elasticsearch.gradle.BuildPlugin.configureRepositories(BuildPlugin.groovy:109)
    at org.elasticsearch.gradle.BuildPlugin$configureRepositories$0.callStatic(Unknown Source)
    at org.elasticsearch.gradle.BuildPlugin.apply(BuildPlugin.groovy:41)
    at org.elasticsearch.gradle.BuildPlugin.apply(BuildPlugin.groovy)
    at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
    at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:44)
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
    ... 58 more


BUILD FAILED

Total time: 4.553 secs
```

**Comment by rjernst** [comment]
The code is this:
```
project.configurations.compile.dependencies.all { dep ->
    if (!(dep instanceof ProjectDependency) && dep.getGroup() != 'org.elasticsearch') {
        dep.transitive = false
    }
}
```
This means `dep` is null, which should be impossible since are iterating the dependencies...

**Comment by clintongormley** [comment]
@rjernst is this still an issue?

**Comment by rjernst** [comment]
We still get failures. First, we can't even run a build normally because we check for `jps` existing, which does not come with the ibm jdk. If I disable that check and just run `gradle test` in core, I see tons of access control failures because mockito under ibm jdk appears to use some different internal classes for proxy construction which our securemock does not add permissions for.
https://gist.github.com/rjernst/c8af285eeb3336488338ed455ff65800

I don't plan to work on this, but thought I would at least update to confirm there are still problems, even if not the original problems this issue was created for.

**Comment by rmuir** [comment]
I discussed with ryan, the security issue is because mockito et all are using internal apis to do evilish stuff. So of course its not guaranteed they use the same one on IBM :) We just have to give mockito jar another permission in the `test-framework.policy` and then it works.

**Comment by rjernst** [comment]
I pushed fa77d4d with the test permission updates. The remaining test failures in core are for probes:
```
Suite: org.elasticsearch.monitor.process.ProcessProbeTests
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=5F652E0448DCAB4D -Dtests.class=org.elasticsearch
.monitor.process.ProcessProbeTests -Dtests.method="testProcessStats" -Dtests.security.manager=true -
Dtests.locale=en-IE -Dtests.timezone=Pacific/Wake
FAILURE 0.02s J3 | ProcessProbeTests.testProcessStats <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: a value greater than <0L>
   >      but: <-1L> was less than <0L>
   >    at __randomizedtesting.SeedInfo.seed([5F652E0448DCAB4D:1433482120E002E]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.monitor.process.ProcessProbeTests.testProcessStats(ProcessProbeTests.ja
va:56)
   >    at java.lang.Thread.run(Thread.java:785)
```

It would appear the jmx beans we use are not all available in ibm jdk.

**Comment by shahidhs-ibm** [comment]
@rmuir I am curious to know which Elasticsearch version you were working on? I believe at the time when you created this post, Elasticsearch was using Maven and not Gradle.
@rjernst We are trying to build Elasticsearch with IBM Java and still getting same issue. Do you have any plans to provide IBM Java support?

**Comment by nik9000** [comment]
> We are trying to build Elasticsearch with IBM Java and still getting same issue. Do you have any plans to provide IBM Java support?

I don't believe we have plans to support the IBM JDK. Maybe one day, not now though.
