### ISSUE TITLE
Client nodes don't report each other [2.1.x]

### ISSUE THREAD

**Issue by bdharrington7** [elastic/elasticsearch#18100]
I've found that when I turn on the client setting (master: false, data: false) in testing a cluster on 2.1, when querying the `_nodes` endpoint from a client node, it won't show other client nodes, but if I query the `_nodes` endpoint from a data node, it will show all client nodes. I've tried this same scenario on elasticsearch version 1.7.4, and I can see all client nodes from any node. 

This issue is also mentioned [here](https://github.com/mobz/elasticsearch-head/issues/246)

**Comment by javanna** [comment]
This should be fixed with #16898 in master and released with 5.0-alpha1. Note also that setting master and data to false was not always the same as setting client to true. That was solved with #16963.

**Comment by bdharrington7** [comment]
Thanks @javanna! Will this be back ported to 2.x?

**Comment by javanna** [comment]
Hi @bdharrington7 no it wasn't backported to 2.x and I am not sure it is safe to do.

**Comment by bdharrington7** [comment]
Ah cool, this looks like we can still get expected behavior by using `node.master: false` and `node.data: false` for a client node

**Comment by javanna** [comment]
right, not sure if that is good or bad though :)
