### ISSUE TITLE
[parent] Data too large, data for [<http_request>] would be larger than limit of

### ISSUE THREAD

**Issue by damm** [elastic/elasticsearch#18221]
Actual error message is here.
```json
{"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be larger than limit of [1478832947/1.3gb]","bytes_wanted":1478843760,"bytes_limit":1478832947}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be larger than limit of [1478832947/1.3gb]","bytes_wanted":1478843760,"bytes_limit":1478832947},"status":503}
```

**Elasticsearch version**: 5.0Alpha2

**JVM version**:
```
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```
**OS version**:
LXC Guest running Ubuntu 14.04
**Description of the problem including expected versus actual behavior**:
Elasticsearch complains about [<http_request>] would be larger than limit after awhile.  I can restart Elasticsearch with more memory to give it more time until it occurs again.

I use Logstash for Injestion; no X-Pack plugin installed.  

**Steps to reproduce**:
 1. Tarball installation of Elasticsearch 5.0Alpha2
 2. Tarball Installation of Logstash
 3. Forward logs until it complains it has run out of memory and starts rejecting writes

Let me know if you want My Logstash configuration and a sample of my logs; I don't think they have anything to do with it as it's a pretty old setup that has worked for awhile and I haven't added any new log sources nor am I dealing with weird Java hacks.

**Provide logs (if relevant)**:

```
[2016-05-09 19:19:33,099][WARN ][rest.suppressed          ] /_bulk Params: {}
CircuitBreakingException[[parent] Data too large, data for [<http_request>] would be larger than limit of [1478832947/1.3gb
]]
        at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService
.java:211)
        at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreak
er.java:128)
        at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:109)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:489)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:65)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.
java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:85)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.
java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.
java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.
java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.
java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:83)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment]
Hi @damm 

Thanks for trying out alpha2!  This issue should be fixed by https://github.com/elastic/elasticsearch/pull/18204 which will be out in the next release.  Would you mind testing it out once released and reporting back if you see similar problems?

**Comment by damm** [comment]
Would love to :) I'll check back when Alpha3 is released.

**Comment by ayadav77** [comment]
Hi @damm were you able to validate if Alpha3 fixed this issue for you? I ask because, I am on Alpha4 and I am seeing this exact issue. Thanks.

**Comment by clintongormley** [comment]
@ayadav77 this issue was fixed in alpha3 - If you're seeing the same thing (as opposed to sending one too-large request) then please open a new issue

**Comment by ayadav77** [comment]
Ok thanks. I will create a new issue as I am seeing a very similar behavior where after sending multiple small bulk requests, eventually i get the error of data too large.

**Comment by damm** [comment]
I never really need test that Alpha3 fixed it because I really don't like running with a broken setup that eventually OOM's my servers..

**Comment by clintongormley** [comment]
@damm It's an alpha.  We warn you not to use alpha releases in production

**Comment by damm** [comment]
@clintongormley it's my test servers; still having them randomly go out isn't much fun either.  You expect your test environment to be a little uppity granted.

I just didn't want to install alpha3 and then waiting 1-2weeks for it to OOM

I could remove extra ram but :(
