### ISSUE TITLE
Short build hash prevents downloading source from Github

### ISSUE THREAD

**Issue by karmi** [elastic/elasticsearch#44323]
**Elasticsearch version** (`bin/elasticsearch --version`):

```
docker run --rm -it docker.elastic.co/elasticsearch/elasticsearch-oss:7.3-SNAPSHOT elasticsearch --version
Version: 7.3.0-SNAPSHOT, Build: oss/docker/ef16bea/2019-07-14T10:46:49.321611Z, JVM: 12.0.1
```

**Description of the problem including expected versus actual behavior**:

The short build hash (referencing the Git commit) in output of the "Info" API (`curl localhost:9200`) prevents downloading the source code from Github, possibly due to ambiguity of the short commit SHA1.

This is breaking eg. the CI for the [Go client](https://clients-ci.elastic.co/job/elastic+go-elasticsearch+7.x/ELASTICSEARCH_VERSION=7.3-SNAPSHOT,GO_VERSION=1-alpine,TEST_SUITE=core,label=linux/58/console).

Also, the Github UI with the short hash returns a `404 NotFound` error, as opposed to longer hash, or the full commit SHA1.

**Steps to reproduce**:

1. Run the current `7.3-SNAPSHOT` version with Docker:

```
$ docker run --rm -it --name estest --env "discovery.type=single-node" --publish 9200:9200 docker.elastic.co/elasticsearch/elasticsearch-oss:7.3-SNAPSHOT
```

2. Display the cluster info and make note of the `build_hash` property:

```
curl -s localhost:9200 | jq -r '.version.build_hash'
# => ef16bea
```

3. Try to download the source at that particular commit, based on the 7-character value, from Github:

```
curl -I https://codeload.github.com/elastic/elasticsearch/zip/ef16bea
HTTP/1.1 404 Not Found
```

Downloading with the 11-character commit SHA1 works:

```
curl -I https://codeload.github.com/elastic/elasticsearch/zip/ef16bea1d2d
HTTP/1.1 200 OK
```

As well as with the full commit SHA1:

```
curl -I https://codeload.github.com/elastic/elasticsearch/zip/ef16bea1d2dec5f6a32547426c9e3f8fed17bb2b
HTTP/1.1 200 OK
```

4. Try to display the Github UI page for the commit referenced by the short hash:

Open https://github.com/elastic/elasticsearch/commit/ef16bea in your browser. A 404 page is displayed.

The [longer build hash version](https://github.com/elastic/elasticsearch/commit/ef16bea1d2d) works, as well as the [full commit SHA1](https://github.com/elastic/elasticsearch/commit/ef16bea1d2dec5f6a32547426c9e3f8fed17bb2b).

**Steps to fix**:

Given the ever-increasing amount of commits in the Elasticsearch repository, I think we should switch to the full, 40-characters long build hashes.

**Comment by karmi** [comment]
I've been hit by the issue again, on current `7.x` version:

```
curl -IL https://github.com/elastic/elasticsearch/archive/3081fd2.zip
....
HTTP/1.1 404 Not Found
```

**Comment by atorok** [comment]
Fixed by #45163

**Comment by karmi** [comment]
Thanks!

**Comment by atorok** [comment]
@mark-vieira I'm reopening this because it's a problem on the `6.8` branch as well. #45163 will probably not back-port there, so we'll need to work out a solution there ,

**Comment by karmi** [comment]
Thanks for re-opening it, @atorok.

For context: from time to time, when Git cannot point to a single commit from the short SHA1, the CI for https://github.com/elastic/go-elasticsearch fails, since it cannot download the archive.

Currently, this is the problematic SHA1:

```
# In the elasticsearch/elasticsearch repository:
$ git show d88965a
error: short SHA1 d88965a is ambiguous
hint: The candidates are:
hint:   d88965a7531 commit 2019-11-17 - CCR should auto-retry rejected execution exceptions (#49213)
hint:   d88965a6628 tree
```

**Comment by mark-vieira** [comment]
@karmi can you confirm this is still an issue for the Go client when building against 6.8 snapshots? Are all other branches still working fine with the fix referred to above?

**Comment by karmi** [comment]
I can confirm — when running the curl command against the updated 6.8-SNAPSHOT version, I'm getting:

```
curl -s localhost:9200 | jq -r '.version.build_hash'
d88965a
```

The `elasticsearch --version` command seems to confirm it; on the 7.5-SNAPSHOT version, I'm getting:

```
docker run --rm -it docker.elastic.co/elasticsearch/elasticsearch-oss:7.5-SNAPSHOT elasticsearch --version
Version: 7.5.0-SNAPSHOT, Build: oss/docker/23df04b7393c429512df0cc6b3510cd1d589a4c5/2019-11-15T14:08:47.494517Z, JVM: 13.0.1
```

On the 6.8-SNAPSHOT version, I'm getting:

```
docker run --rm -it docker.elastic.co/elasticsearch/elasticsearch-oss:6.8-SNAPSHOT elasticsearch --version
Version: 6.8.5-SNAPSHOT, Build: oss/docker/d88965a/2019-11-19T16:43:58.556367Z, JVM: 13.0.1
```

Notice the short hash. So yes, the master and 7.x branches work fine, the 6.x still has the old, short build hash.

**Comment by mark-vieira** [comment]
Are your 6.8 builds broken at the moment. Just trying to get an idea of prioritization for this issue.

**Comment by karmi** [comment]
It's not super-urgent — I can always wait couple of days for a new Docker image, or run the tests manually if needed. Also, 6.x is not a "hot" branch/version. But it would be better to fix it eventually, I think, because the short hash is ambiguous.

**Comment by mark-vieira** [comment]
I'm going to pessimistically go ahead and close this. I don't think this is worth the effort to backport to 6.8. Activity in that branch is very minimal, so the likelyhood of encountering a future hash ambiguity is pretty low compared to `7.x` and `master` branches. If this becomes a serious blocker feel free to reopen an issue.
