### ISSUE TITLE
field_caps based on index template and without index - helpful for beats, ingest manager

### ISSUE THREAD

**Issue by mattkime** [elastic/elasticsearch#59448]
The problem -

Our solutions often need to set up dashboards in kibana. Dashboards depend upon the existence of an index pattern. Index patterns are created with the help of the field caps api. The field caps api requires an index to exist. Our solution specifically don't want an index to exist until there are documents. The solutions end up writing index pattern saved objects with code that is separate from the index pattern api.  It is necessary to refresh an index pattern when fields are added. This creates the case where an index pattern may be written from one codebase and updated by another. 

Solution -

The field caps api could return results WITHOUT the presence of an index IF an index template provides field information.

**Comment by jpountz** [comment]
@mattkime We just discussed this and would like to get more context about this request. Is it related to efforts around Ingest Manager to ship dashboards when installing packages? And if we implemented this feature, what would the new workflow look like in Kibana: first Ingest Manager would install the template, then Kibana would call _field_caps to bootstrap the index pattern, and finally dashboards would get installed? Is my understanding correct?

**Comment by jimczi** [comment]
@mattkime , what is the status for this ? Is it still needed ? If so, can you provide the information that Adrien asked ?

**Comment by mattkime** [comment]
@jimczi I should reexamine this in light of recent changes to index patterns and go from there. I'm not certain that this is needed anymore.

**Comment by javanna** [comment]
I am closing this issue due to lack of activity, please feel free to reopen or comment if the requested enhancement comes up again.

**Comment by ruflin** [comment]
@joshdover I think the issue still partially exists as we write index patterns in view but not convinced this one here is the "right" solution.
