### ISSUE TITLE
Security_exception: action [indices:admin/rollover] is unauthorized for user

### ISSUE THREAD

**Issue by hendry-lim** [elastic/elasticsearch#61453]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.0 (Docker)

**OS version** (`uname -a` if on a Unix-like system): Alpine

**Description of the problem including expected versus actual behavior**:
Encountered error: `Security_exception: action [indices:admin/rollover] is unauthorized for user`.
Adding `manage` or `all` privilege on the index level for the role does not seem to work, because the error still appears from time to time.
Also noticed that the error may resolve itself, but it will re-appear again.
[Discuss thread](https://discuss.elastic.co/t/security-exception-action-indices-admin-rollover-is-unauthorized-for-user)
I even changed the user to `beats_writer` in `Heartbeat`, but I am still receiving the same error for `beats_system_custom` user.

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/48344515/90993718-8f71e180-e5e8-11ea-85ed-c45245d06ffd.png)
![image (1)](https://user-images.githubusercontent.com/48344515/90993720-913ba500-e5e8-11ea-81b2-395d9b92f7e5.png)
![image (2)](https://user-images.githubusercontent.com/48344515/90993724-926cd200-e5e8-11ea-8c1d-794da6e8a083.png)
![image (3)](https://user-images.githubusercontent.com/48344515/90993726-94369580-e5e8-11ea-970c-db8e6e0006c6.png)

</details>

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Setup Beats custom role to setup and ingest data
 2. Run either `Auditbeat`, `Heartbeat`, or `Winlogbeat` (error seems to only occur for these 3 Beats indices)
 3. Observe the exception appears in Elasticsearch log

**Provide logs (if relevant)**:

<details>
<summary>Error</summary>

```
{
    "type": "server",
    "timestamp": "2020-08-19T12:08:46,690Z",
    "level": "WARN",
    "component": "o.e.i.s.IndexShard",
    "cluster.name": "docker-cluster",
    "node.name": "es01",
    "message": " [apm-7.9.0-transaction-000001][0] onPreFetchPhase listener [org.elasticsearch.xpack.security.authz.SecuritySearchOperationListener@ccd1c8b] failed",
    "cluster.uuid": "D8swAaZPTDeLax90eETYwg",
    "node.id": "6a3KukJsTrqiibIoFlOQ8A",
    "stacktrace": ["org.elasticsearch.ElasticsearchSecurityException: [[FAOfBnQBQcojp3HWI0Vd][23968]] expected scroll indices access control [IndicesAccessControl{granted=true, indexPermissions={apm-7.9.0-error=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-span=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-metric=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-onboarding-2020.08.18=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-transaction-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-metric-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-onboarding=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-profile-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-error-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-span-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-profile=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-transaction=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}}}] but found [IndicesAccessControl{granted=true, indexPermissions={apm-7.9.0-error=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-span=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-metric=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-onboarding-2020.08.18=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-transaction-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-metric-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-onboarding=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-profile-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-error-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-span-000001=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-profile=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}, apm-7.9.0-transaction=IndexAccessControl{granted=true, fieldPermissions=org.elasticsearch.xpack.core.security.authz.permission.FieldPermissions@1, documentPermissions=DocumentPermissions [queries=null, scopedByQueries=null]}}}] in thread context",
        "at org.elasticsearch.xpack.security.authz.SecuritySearchOperationListener.ensureIndicesAccessControlForScrollThreadContext(SecuritySearchOperationListener.java:111) ~[?:?]",
        "at org.elasticsearch.xpack.security.authz.SecuritySearchOperationListener.onPreFetchPhase(SecuritySearchOperationListener.java:95) ~[?:?]",
        "at org.elasticsearch.index.shard.SearchOperationListener$CompositeListener.onPreFetchPhase(SearchOperationListener.java:166) [elasticsearch-7.9.0.jar:7.9.0]",
        "at org.elasticsearch.search.SearchService$SearchOperationListenerExecutor.<init>(SearchService.java:1272) [elasticsearch-7.9.0.jar:7.9.0]",
        "at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$4(SearchService.java:584) [elasticsearch-7.9.0.jar:7.9.0]",
        "at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58) [elasticsearch-7.9.0.jar:7.9.0]",
        "at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) [elasticsearch-7.9.0.jar:7.9.0]",
        "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.0.jar:7.9.0]",
        "at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.9.0.jar:7.9.0]",
        "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:710) [elasticsearch-7.9.0.jar:7.9.0]",
        "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.0.jar:7.9.0]",
        "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
        "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
        "at java.lang.Thread.run(Thread.java:832) [?:?]"]
}
```
</details>

**Comment by ywangd** [comment]
The exception shown in the provided log is a known issue and fixed by #61446 and should be released as either v7.9.1 or v7.10.0. Though I am not sure whether this is the root cause of the `rollover` error since the log does not shown anything about rollover. @albertzaharovits

**Comment by hendry-lim** [comment]
I could not find any error log related to the `rollover`, but the `rollover` did not happen and updating the ILM policy did not update the indices policy either. The error for those indices disappeared after I did the `rollover` manually. However, I am still seeing the same errors for data streams.

**Comment by albertzaharovits** [comment]
Hi @hendry-lim ,

Can you please share with us more of the log file?
The `expected scroll indices access control` errors are spurious, and it should be fixed in 7.9.1 .
It is not the root of the problem.

Where do you see the `Security_exception: action [indices:admin/rollover] is unauthorized for user` message?

**Comment by hendry-lim** [comment]
The message `Security_exception: action [indices:admin/rollover] is unauthorized for user` was shown in Kibana.

> The `expected scroll indices access control` errors are spurious, and they should be fixed in 7.9.1.
I will try out `7.9.1` to see if the error persists.

**Comment by hendry-lim** [comment]
Not seeing this error anymore in `7.9.1`, closing this.

**Comment by qfdk** [comment]
We have the same problem using metricbeats 7.9.3 in elk cloud. 

The user we have already deleted but we got the message from the old user.

1.  create new user (metricbeat-new)
2. stop metricbeat and change old user (xxx-metricbeat) by new user (metricbeat-new)
3. start metricbeat with new user (metricbeat-new)
4. via interface kibana, i got the error for old user (xxx-metricbeat)

<img width="884" alt="Snipaste_2020-11-16_18-27-11" src="https://user-images.githubusercontent.com/2404478/99299216-33b39f00-284b-11eb-9c69-a287ae01019c.png">
<img width="1715" alt="Snipaste_2020-11-16_20-35-37" src="https://user-images.githubusercontent.com/2404478/99299284-4fb74080-284b-11eb-8a1e-2e083ecfdb89.png">

**Comment by ywangd** [comment]
An IML policy saves the credentails of the user who modifies it most recently. In your case, the ILM policy, `metricbeat`, was created by the old user `xxx-metricbeat` and the policy internally still references the old user's credentails after you changed the metricbeat user. 
You can make the ILM policy use the new `metricbeat-new` user by performing a no-op update. The steps would be something like the follows:
1. [Retrieve](https://www.elastic.co/guide/en/elasticsearch/reference/master/ilm-get-lifecycle.html) the `metricbeat` policy with `GET _ilm/policy/metricbeat`. 
2. Take the response from the previous step and modify it so it can be used as an input for [update](https://www.elastic.co/guide/en/elasticsearch/reference/master/ilm-put-lifecycle.html). Please make sure the input is identical to the existing policy, i.e. the update will be a no-op (except the saved credentials)
3. As the new user `metricbeat-new`, issue an update ILM policy call with input from the previous step. The update call will capture the calling user's credentials (`metricbeat-new`) and drop the old one (`xxx-metricbeat`).

**Comment by qfdk** [comment]
@ywangd Thanks for your explications. 

We have different accounts to separate the environment,
now we have "metricbeat-new-dev" and "metricbeat-new-prod", two accounts have the same privileges and they will write to the same index (metricbeat-date-00001). The production account isn't active

I want to know if we will get the same issue when the production account actives?

Best regards

**Comment by ywangd** [comment]
@qfdk Thanks very much for your interest in Elasticsearch. 

I forgot to mention it earlier, but the error you got is different from the one that this issue is about (if you compare the stacktraces, they are different). This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question.

**Comment by qfdk** [comment]
@ywangd Thank you. I will send it to the forum
