### ISSUE TITLE
[CI] Failure in TimeThrottleIntegrationTests.testTimeThrottle

### ISSUE THREAD

**Issue by csoulios** [elastic/elasticsearch#65176]
Failure in this build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian-10&&immutable/350/console

**Repro line**:

REPRODUCE WITH: 
```
./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.testTimeThrottleDefaults" \
  -Dtests.seed=A37E9D67313077DA \
  -Dtests.security.manager=true \
  -Dtests.locale=hi \
  -Dtests.timezone=America/Monterrey \
  -Druntime.java=11
```

**Reproduces locally?**:

Reproduces locally

**Build scan**:

https://gradle-enterprise.elastic.co/s/3ljbnlzegok2e/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests/testTimeThrottleDefaults?expanded-stacktrace=WyIwIl0

**Applicable branches**:

**Failure history**:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:%22testTimeThrottleDefaults%22'),sort:!(time,desc))

**Failure excerpt**:

```
08:32:54 > Task :x-pack:plugin:watcher:internalClusterTest
08:32:54 
08:32:54 
08:32:54 org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests > testTimeThrottleDefaults FAILED
08:32:54     java.lang.AssertionError: watch was triggered on [0] schedulers, expected [1]
08:32:54     Expected: a value equal to or greater than <1L>
08:32:54          but: <0L> was less than <1L>
08:32:54         at __randomizedtesting.SeedInfo.seed([A37E9D67313077DA:1F509B95C0A90AB0]:0)
08:32:54         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
08:32:54         at org.junit.Assert.assertThat(Assert.java:956)
08:32:54         at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase$TimeWarp.trigger(AbstractWatcherIntegrationTestCase.java:606)
08:32:54         at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase$TimeWarp.trigger(AbstractWatcherIntegrationTestCase.java:591)
08:32:54         at org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.testTimeThrottleDefaults(TimeThrottleIntegrationTests.java:71)
08:32:54 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
08:32:56 REPRODUCE WITH: ./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.testTimeThrottleDefaults" -Dtests.seed=A37E9D67313077DA -Dtests.security.manager=true -Dtests.locale=hi -Dtests.timezone=America/Monterrey -Druntime.java=11



```

**Comment by davidkyle** [comment]
Another https://gradle-enterprise.elastic.co/s/4bc4jfl2uvtzs

Both `testTimeThrottle` and `testTimeThrottleDefault` failed in the above

**Comment by probakowski** [comment]
Should be fixed by #65186

**Comment by nik9000** [comment]
Is this the same bug, come back to haunt us?
```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8


org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests > testTimeThrottle FAILED
    java.lang.AssertionError: Count is 4 hits but 3 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
        at __randomizedtesting.SeedInfo.seed([172C76E9B6DD76BD:F9803FCC9AFBBA44]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:270)
        at org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.assertTotalHistoryEntries(TimeThrottleIntegrationTests.java:119)
        at org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.testTimeThrottle(TimeThrottleIntegrationTests.java:57)
:x-pack:plugin:sql:qa:jdbc:single-node:v7.11.0#bwcTest
REPRODUCE WITH: ./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests.testTimeThrottle" -Dtests.seed=172C76E9B6DD76BD -Dtests.security.manager=true -Dtests.locale=zh-TW -Dtests.timezone=Asia/Saigon -Druntime.java=11

Suite: Test class org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests
  1> [2020-11-24T23:39:15,849][INFO ][o.e.x.w.a.TimeThrottleIntegrationTests] [testTimeThrottle] before test
```

**Comment by nik9000** [comment]
Again again? https://gradle-enterprise.elastic.co/s/m42e3ixd3otfc/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.actions.TimeThrottleIntegrationTests/testTimeThrottle#1

**Comment by jaymode** [comment]
I see this is still occurring on master: https://gradle-enterprise.elastic.co/s/5wfibylhxvfu2

**Comment by tlrx** [comment]
This happened again today: https://gradle-enterprise.elastic.co/s/4nkttucbmg2ew

**Comment by tlrx** [comment]
The test `testTimeThrottleDefaults` (which is the one in the description of this issue) failed again today:
 https://gradle-enterprise.elastic.co/s/4nkttucbmg2ew

**Comment by tlrx** [comment]
I muted the test `testTimeThrottleDefaults` in master (f460b98ae0862452696d60dee9327160aca7b2d6)
