### ISSUE TITLE
Netty4HeadBodyIsEmptyIT.testTemplateExists fails in fips mode

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#66820]
**Build scan**: https://gradle-enterprise.elastic.co/s/uyhi5qrl4il5m

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':modules:transport-netty4:javaRestTest' --tests "org.elasticsearch.rest.Netty4HeadBodyIsEmptyIT.testTemplateExists" -Dtests.seed=929C4965732D9139 -Dtests.security.manager=true -Dtests.locale=zh-CN -Dtests.timezone=Asia/Vladivostok -Druntime.java=11 -Dtests.fips.enabled=true
```
**Reproduces locally?**: yes

**Applicable branches**: master 

**Failure history**:

**Failure excerpt**:

```
org.elasticsearch.rest.Netty4HeadBodyIsEmptyIT > testTemplateExists FAILED |  
-- | --
  | org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:35925], URI [/_template/template], status line [HTTP/1.1 200 OK] |  
  | Warnings: [legacy template [template] has index patterns [*] matching patterns from existing composable templates [ilm-history,.watch-history-14,.triggered_watches,.slm-history,synthetics,metrics,.deprecation-indexing-template,.watches,logs] with patterns (ilm-history => [ilm-history-5*],.watch-history-14 => [.watcher-history-14*],.triggered_watches => [.triggered_watches*],.slm-history => [.slm-history-5*],synthetics => [synthetics-*-*],metrics => [metrics-*-*],.deprecation-indexing-template => [.logs-deprecation-elasticsearch],.watches => [.watches*],logs => [logs-*-*]); this template [template] may be ignored in favor of a composable template at index creation time] |  
  | {"acknowledged":true} |  
  | at __randomizedtesting.SeedInfo.seed([929C4965732D9139:416DB177AAD2AE0A]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.rest.Netty4HeadBodyIsEmptyIT.testTemplateExists(Netty4HeadBodyIsEmptyIT.java:137) 
```

This might be caused again by the fact that we force the default distribution to be used instead which causes some default templates to be installed. We can either skip this in fips mode or acknowledge the warning header in fips mode

**Comment by mayya-sharipova** [comment]
There are 58 failures of this test in the last 7 days, only in FIPS mode.
The last failure on 7.x branch is: 

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA=adoptopenjdk11,nodes=general-purpose/433/console
Build Scans: https://gradle-enterprise.elastic.co/s/udxr2d4zcb4ky

**Comment by tvernum** [comment]
We already attempt to handle this warning in FIPS mode:
- https://github.com/elastic/elasticsearch/blob/5b6675ab0d79af6ce566e7956d19dcb89fb0a507/modules/transport-netty4/src/javaRestTest/java/org/elasticsearch/rest/Netty4HeadBodyIsEmptyIT.java#L127-L136

However the warning that we're expecting is quite not the same as the one being generated
```
 legacy template [template] has index patterns [*] matching patterns from existing composable templates
-[ilm-history,.triggered_watches,.watch-history-14,.slm-history,synthetics,metrics,.deprecation-indexing-template,.watches,logs]
+[ilm-history,.watch-history-14,.triggered_watches,.slm-history,synthetics,metrics,.deprecation-indexing-template,.watches,logs]
  with patterns (ilm-history =>
-[ilm-history-5*],.triggered_watches
+[ilm-history-5*],.watch-history-14
  =>
-[.triggered_watches*],.watch-history-14
+[.watcher-history-14*],.triggered_watches
  =>
-[.watcher-history-14*],.slm-history
+[.triggered_watches*],.slm-history
  => [.slm-history-5*],synthetics => [synthetics-*-*],metrics => [metrics-*-*],.deprecation-indexing-template => [.logs-deprecation-elasticsearch],.watches => [.watches*],logs => [logs-*-*]); this template [template] may be ignored in favor of a composable template at index creation time
```

It looks like an ordering issue - I don't know whether the order has intentionally changed since we add the `expectWarnings`, or whether it's non-deterministic.

**Comment by javanna** [comment]
This test fails again: https://gradle-enterprise.elastic.co/s/6rmcxaqirvfnu/tests/:modules:transport-netty4:javaRestTest/org.elasticsearch.rest.Netty4HeadBodyIsEmptyIT/testTemplateExists

**Comment by javanna** [comment]
I've muted this test in 7.x

**Comment by ywangd** [comment]
Should be fixed by #67875

**Comment by mark-vieira** [comment]
This started happening again yesterday on both master and 7.x.

https://gradle-enterprise.elastic.co/s/zzsnslhscjka2/tests/:modules:transport-netty4:javaRestTest/org.elasticsearch.rest.Netty4HeadBodyIsEmptyIT/testTemplateExists#1

**Comment by DaveCTurner** [comment]
This also fails on 7.12:

- https://gradle-enterprise.elastic.co/s/y4kzvqamy2rpu
- https://gradle-enterprise.elastic.co/s/jwvyrluy4sln2
- https://gradle-enterprise.elastic.co/s/2uwqza56aj5cw
- https://gradle-enterprise.elastic.co/s/idnqej24ogeee
- https://gradle-enterprise.elastic.co/s/vph3j6sdxa5hg
- https://gradle-enterprise.elastic.co/s/llvezg3ry2u2i
- https://gradle-enterprise.elastic.co/s/tcjjk4av2ltoe

Hopefully just a missing backport?

**Comment by ywangd** [comment]
The failure is due to this new change to 7.12 branch (https://github.com/elastic/elasticsearch/pull/69537). It removed the deprecation index template. I'll raise a PR for it. Thanks!

**Comment by ywangd** [comment]
Fixed by #69793

**Comment by tvernum** [comment]
@ywangd @jkakavas I don't understand why this keeps failing for FIPS (only).

With the OSS distribution removed, the issue of "FIPS test run the default distribution" shouldn't matter anymore - that's going to be true for all tests, so why do we still have a difference?

**Comment by ywangd** [comment]
I think the direct reason is that the non-FIPS tests use the [INTEG_TEST](https://github.com/elastic/elasticsearch/blob/master/buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestDistribution.java#L14) distribution, which does not have any x-pack plugins. But I am not sure how it is done or why/whether it is necessary/relevant given the license change. @mark-vieira Could you please help out here?

**Comment by tvernum** [comment]
As this issue shows, it's a constant effort to keep some of these tests working on FIPS when they runs a different distribution than the non-FIPS test.
I don't think we can keep patching the problem, we need a more stable solution.

**Comment by mark-vieira** [comment]
> I think the direct reason is that the non-FIPS tests use the INTEG_TEST distribution, which does not have any x-pack plugins. But I am not sure how it is done or why/whether it is necessary/relevant given the license change. @mark-vieira Could you please help out here?

It's not clear to my why FIPS testing needs to override the distribution type. The purpose of the INTEG_TEST distribution is to have a distribution with a much smaller footprint for testing plugins/modules. Going forward the usage of this distribution will _increase_ not decrease as we want to expand the benefits of doing such like faster startup times and better build cache hit rates.

If this disparity between how FIPS vs non-FIPS tests execute continues to be a problem then maybe we need to revisit the need to run FIPS tests against the default distro. Again, I don't have enough context to know why this is done. Perhaps we can solve the root problem here and allow the FIPS tests to us the INTEG_TEST distribution.

**Comment by jkakavas** [comment]
> It's not clear to my why FIPS testing needs to override the distribution type. 

We couldn't use the INTEG_TEST distribution for fips. The most prominent error I remember is that we can't set xpack.security.fips_mode.enabled: true setting in the INTEG_TEST distribution
```
 java.lang.IllegalArgumentException: unknown setting [X] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
 ```
 
 I'm not familiar with how integ_test distribution is built and what is lacking, but I think we can work towards figuring out along with the es-delivery folks. My concern is that the more the integ_test differs from default distribution the less certain we can be that we're actually testing how our clusters behave in a fips 140 JVM. Again, I lack insights but I'm willing to find out.

**Comment by mark-vieira** [comment]
If we could simply conditionally add that setting based on distribution type would that suffice?

**Comment by mark-vieira** [comment]
>  My concern is that the more the integ_test differs from default distribution the less certain we can be that we're actually testing how our clusters behave in a fips 140 JVM.

I don't think that's a concern because there are still loads of integration tests that use (and will continue to use) the default distro.

**Comment by jkakavas** [comment]
> If we could simply conditionally add that setting based on distribution type would that suffice?

Not sure I follow this. We want the clusters that we use in integration tests in fips mode to have this setting on, because we expect users to set this setting when they run es in fips mode and this provides us the best coverage. Why would we want to not set it when INTEG_TEST distro is used ? I think this solves the problem backwards. 

> I don't think that's a concern because there are still loads of integration tests that use (and will continue to use) the default distro.

Isn't this contradicting with "Going forward the usage of this distribution will increase not decrease" ?

**Comment by mark-vieira** [comment]
> Why would we want to not set it when INTEG_TEST distro is used ? I think this solves the problem backwards.

I think we can actually make this simpler. The issue is that in tests for non-xpack modules, this setting doesn't exist. Therefore we already aren't _really_ testing this feature because all we are doing is replacing the distribution type, but the _tests_ aren't exercising x-pack code so the setting superfluous.

What we should be doing is only adding the setting for x-pack projects.

> Isn't this contradicting with "Going forward the usage of this distribution will increase not decrease" ?

Decrease, but won't completely go away. I think we tend to get distracted by the phrase "testing the default distro". We aren't _really_ testing it if the tests don't exercise any of those code paths. We have loads of tests that still use the "full" distribution, like BWC tests and Packaging tests. But consider if I'm testing a module, say data-streams, it makes no sense to also have `sql` installed, and if I do, the test coverage won't ever touch that code anyhow.

I don't want to get too far in the weeds of why we want modularized testing, this isn't the place. The point being that we want FIPS testing and non-FIPS testing to be as similar as possible.  If we can adapt the FIPS stuff such that it can work with the INTEG_TEST distribution we should aim to do so, rather than force the default distribution everywhere and then have to constantly deal with these annoying issues that come from that disparity.

**Comment by jkakavas** [comment]
> What we should be doing is only adding the setting for x-pack projects.

++ Sounds good to me. 

> I don't want to get too far in the weeds of why we want modularized testing, this isn't the place.

Never meant to question that :)

>  If we can adapt the FIPS stuff such that it can work with the INTEG_TEST distribution we should aim to do so,

:+1:  We actually also had this discussion back in December  in slack. At that point we were not that concerned about this but we were looking at it from the perspective of smaller footprint and cacheabilty only. The issue of

> then have to constantly deal with these annoying issues that come from that disparity.

tips the scale I guess. I'll open an issue to look into not forcing a specific distro in `fips.gradle` but rather depend on what the project already does and how we can make this work

**Comment by mark-vieira** [comment]
Thanks @jkakavas, yeah, I think at the time we just wanted the shortest road here and perhaps didn't anticipate that this differentiation would lead to test issues besides just worse cache performance. Given there are other negative side effects of that approach I think we agree it makes sense to press forward with using INTEG_TEST where possible.
