### ISSUE TITLE
Combined_fields query not behaving correctly inside bool query under certain circumstances

### ISSUE THREAD

**Issue by nemphys** [elastic/elasticsearch#75223]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.3

**Plugins installed**: [ analysis_icu ]

**JVM version** (`java -version`): bundled

**OS version** (`uname -a` if on a Unix-like system): macOS Big Sur

**Description of the problem including expected versus actual behavior**:

As already reported in the last comments of #74037, I am facing a weird issue where a boolean should query containing various combined_fields queries returns no results under certain circumstances.
I have tried adjusting the query in many different ways in order to find what the cause could be, but the findings are quite confusing.

The base (greatly simplified) query that produces no results is as follows (please note that fields have been split into separate combined_fields queries according to their *search_analyzer* as they are supposed to and the only field that should return matches in this case is the 'id.ngram' field of the 3rd query):
```javascript
{
    "query": {
        "bool": {
            "should": [
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "name",
                            "description",
                            "manufacturer",
                            "category",
                            "category_leaf",
                            "color",
                            "sizes"
                        ]
                    }
                },
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "name.std",
                            "description.std",
                            "manufacturer.std",
                            "category.std",
                            "category_leaf.std",
                            "color.std",
                            "sizes.std"
                        ]
                    }
                },
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "id",
                            "mpn",
                            "id.ngram",
                            "mpn.ngram"
                        ]
                    }
                }
            ]
        }
    }
}
```

Queries that *do* return the expected results are:

1) Removal of the 2nd query (which is base on a [ "fold", "lowercase", "stop" ] token filter analyzer):
```javascript
{
    "query": {
        "bool": {
            "should": [
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "name",
                            "description",
                            "manufacturer",
                            "category",
                            "category_leaf",
                            "color",
                            "sizes"
                        ]
                    }
                },
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "id",
                            "mpn",
                            "id.ngram",
                            "mpn.ngram"
                        ]
                    }
                }
            ]
        }
    }
}
```

Please note that removing the first query (same fields as the second, but with a more complex analyzer) does *not* fix the problem. Needless to say that removing both the first and the second queries *does* return results.

2) Removal of all fields of the second query except for one (does not matter which one, have tried all of them):
```javascript
{
    "query": {
        "bool": {
            "should": [
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "name",
                            "description",
                            "manufacturer",
                            "category",
                            "category_leaf",
                            "color",
                            "sizes"
                        ]
                    }
                },
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "name.std"
                        ]
                    }
                },
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "id",
                            "mpn",
                            "id.ngram",
                            "mpn.ngram"
                        ]
                    }
                }
            ]
        }
    }
}
```

3) Removal of all fields of the third query, except (of course) for 'id.ngram' (which is the matching field):
```javascript
{
    "query": {
        "bool": {
            "should": [
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "name",
                            "description",
                            "manufacturer",
                            "category",
                            "category_leaf",
                            "color",
                            "sizes"
                        ]
                    }
                },
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "name.std",
                            "description.std",
                            "manufacturer.std",
                            "category.std",
                            "category_leaf.std",
                            "color.std",
                            "sizes.std"
                        ]
                    }
                },
                {
                    "combined_fields": {
                        "query": "xxxxx",
                        "operator": "AND",
                        "fields": [
                            "id.ngram"
                        ]
                    }
                }
            ]
        }
    }
}
```

@jtibshirani please take a look at this, might ring a bell somehow.

**Comment by jtibshirani** [comment]
@nemphys I am stumped and don't have an idea about what could be wrong. It's very surprising behavior: removing a `should` clause from a `bool` query should never result in *more* results being returned. Do you find any more ideas/ insights into the problem?

**Comment by nemphys** [comment]
No clue, but until this is figured out, combined_fields is definitely not ready for prime time. Could the n-gram analysis have anything to do with it?

**Comment by jtibshirani** [comment]
Inspiration struck and I have an idea as to what is wrong. I noticed that the Lucene query implements `equals` and `hashCode` incorrectly. As an optimization, `bool` queries try to deduplicate clauses, so it is accidentally removing the third query during this optimization. To test this theory, you can try passing your query to the `validate` API, making sure to pass the `rewrite` parameter: https://www.elastic.co/guide/en/elasticsearch/reference/7.13/search-validate.html#_the_rewrite_parameter. I suspect the optimized query that comes back will be missing important clauses.

This is another serious bug :( I'll try to get it fixed in an upcoming patch release. I'll also raise an issue in Lucene to discuss how we can prevent shipping these sorts of bugs in the future.

**Comment by nemphys** [comment]
Indeed, using the validate API I can confirm that the produced Lucene query is missing the 3rd query altogether. Great find, I hope the PR fixes this, since it is quite a bug (I also tried my non-simplified version of the query with 6 combined_fields branches and I think that just 2 of them made it to the final Lucene query :-))

**Comment by nemphys** [comment]
I suppose this did not make it in 7.13.4, since the issue still remains in this version. Please confirm!

**Comment by jtibshirani** [comment]
Yes, we unfortunately didn't make the cut-off for 7.13.4. It will be available in the next release after that.

**Comment by jtibshirani** [comment]
@nemphys thanks again for uncovering these bugs. Did you get the chance to try out the 7.14 release, and if so is it working as intended? I ask because we are working on a Lucene upgrade (https://github.com/elastic/elasticsearch/pull/77801) and I'd like to remove our custom fork of `CombinedFieldQuery` if no more changes are needed.

**Comment by nemphys** [comment]
I switched to 7.14 as soon as it was released and I am happy to say that, apart from the fact that this issue has indeed been fixed, I have not had any other issues with combined_fields so far.
I will be extensively testing the search functionality (and performance) of the new product I am currently working on next month (been dealing with other stuff lately), so I will report anything new I come by then.
